const itineraryData = [
{day:1,
date:"Giovedì 06/08/2026",
title:"Arrivo a Los Angeles",
route:"LAX ➔ West Hollywood",
km:37,
time:"1h",
sunrise:"06:08", // ok
sunset:"19:48", // ok
fuso:"Pacific Time (GMT-7)",
hotel:"Hotel Ziggy on Sunset West Hollywood",
desc:"Atterraggio a LAX alle 14:55 con volo British da Londra. Considerare 60-90 min per controlli, bagagli, ritiro auto e uscita dall'aeroporto. Trasferimento in hotel e tramonto al <strong>Griﬃth Observatory</strong>. Serata tranquilla in zona <strong>West Hollywood</strong>",
//logistics:"Auto prenotata con Alamo.",
transferInfo:"<p>Dopo aver superato i controlli doganali e ritirato i bagagli per raggiungere il lotto auto Alamo uscire dal terminal e seguire i cartelli viola o arancioni con la scritta <strong>Rental Car Shuttles</strong>. Attendere il passaggio dell'autobus navetta gratuito. Il tragitto durerà circa 10-15 minuti. Dirigersi direttamente al lotto di veicoli Alamo per scegliere un veicolo. Le chiavi si troveranno in macchina e la prenotazione sarà verificata alla cabina di uscita del lotto. <br> ⚠️ <strong>Importante:</strong> Aver già fatto il check-in online e inserito i dettagli della carta di credito </p>",
food:["Saddle Ranch Chop House","Mels Drive-In","Carney's Restaurant"],
pranzo:["A bordo dell'aereo"],
region:"California",
gmaps:"https://maps.google.com/?q=Osservatorio+Griffith+Los+Angeles",
phaseId:"phase1"},

{day:2,
date:"Venerdì 07/08/2026",
title:"Beverly Hills, Rodeo Drive, Santa Monica & Venice Beach",
route:"West Hollywood ➔ Beverly Hills ➔ Rodeo Drive ➔ Santa Monica ➔ Venice Beach ➔ West Hollywood",
km:48,
time:"1h",
sunrise:"06:09", // ok
sunset:"19:47", // ok
fuso:"Pacific Time (GMT-7)",
hotel:"Hotel Ziggy on Sunset West Hollywood",
desc:"Partenza dall’hotel in direzione <strong>Beverly Hills</strong> e <strong>Rodeo Drive</strong> poi verso <strong>Santa Monica Pier</strong> per pranzo e passeggiata fino a <strong>Venice Beach</strong>. Tramonto a Santa Monica (distanza hotel - Santa Monica circa 25’) <br>Rientro in hotel, cena e a spasso per la città",
//logistics:"Venice Beach Parking Lot o lotti su Pacific Ave; a Santa Monica usare Santa Monica Place Parking o Structure 8; a Malibu usare parcheggi ufficiali spiaggia.",
food:["Saddle Ranch Chop House","Mels Drive-In","Carney's Restaurant"],
pranzo:["Pier Burger","The Albright"],
region:"California",
gmaps:"https://maps.google.com/?q=Santa+Monica+California+Stati+Uniti",
phaseId:"phase1"},

{day:3,
date:"Sabato 08/08/2026",
title:"Route 66 ➔ Kingman",
route:"Los Angeles ➔ Barstow ➔ Amboy ➔ Oatman ➔ Kingman",
km:542,
time:"5h45",
sunrise:"06:10", // ok
sunset:"19:31", // ok
fuso:"Pacific Time (GMT-7)",
hotel:"Motel 6-Kingman",
desc:"A spasso per la <strong>Walk of Fame</strong> (Dolby Theatre, TCL Chinese Theatre) e foto scritta <strong>Hollywood</strong> (Lake Hollywwod Park) prima della partenza in mattinata in direzione <strong>Kingman</strong> con tappe sulla <strong>Route 66</strong> (<strong>Barstow</strong> città fantasma, <strong>Amboy, Oatman</strong>)<br> Percorrere la <strong>National Trails Hwy</strong> (passando per <strong>Amboy Roy's Motel & Cafe</strong>) e la <strong>Oatman Highway</strong> con tappa a <strong>Oatman Hotel Restaurant & Bar</strong><br>Arrivo a Kingman, hotel e cena",
//logistics:"Osservatorio Griffith: lasciare auto vicino al Teatro Greco. Hollywood: Hollywood & Highland Parking (6801 Hollywood Blvd). Beverly Hills: Parking 461 N Bedford Dr (prime 2h gratis). Bus Sightseeing: fermata Paramount Studios o Dolby Theatre.",
food:["Mr D'z Route 66 Diner (anche colazione)","Black Bear Diner Kingman"],
pranzo:["Pranzo in locale tipico lungo la Route 66"],
region:"Arizona",
gmaps:"https://maps.google.com/?q=Roy's+Motel+%26+Cafe",
phaseId:"phase2"},

{day:4,
date:"Domenica 09/08/2026",
title:"Kingman ➔ Grand Canyon South Rim",
route:"Kingman ➔ Selingman ➔ Williams ➔ Grand Canyon (Tramonto)",
km:305,
time:"3h20",
sunrise:"05:52", //ok
sunset:"19:24", //ok
fuso:"Pacific Time (GMT-7)",
hotel:"Maswik Lodge",
desc:"Partenza in mattinata in direzione <strong>Grand Canyon</strong> con tappe sulla <strong>Route 66</strong> (Selingman, Williams). Impostare sul navigatore Peach Spring per arrivare a Selingman passando per la Route 66 storica <br>Arrivo al <strong>Grand Canyon</strong> per orario tramonto dal South Rim (<strong>Hopi Point</strong> (più popolare - navetta) - <strong>Pima Point</strong> (meno aﬀollato - navetta) - <strong>Yavapai Point</strong> (più comodo perché vicino Visitor Center)). In base all’orario di arrivo valutare la possibilità di fare il giro della <strong>Hermit Road</strong> con navetta (punto di partenza Village Route Transfer (6’ a piedi da alloggio) - 9 fermate all’andata, 3 al ritorno)<br>Rientro in hotel e cena",
//logistics:"Palm Springs: Downtown Palm Springs Parking. Hotel-parco per tramonto: ~1h senza soste. Evitare lunghe camminate nelle ore centrali per caldo intenso.",
food:["Maswik Food Court","Arizona Steakhouse","El Tovar Dining Room"],
pranzo:["Pranzo in locale tipico lungo la Route 66"],
region:"Arizona",
gmaps:"https://maps.google.com/?q=Classic+Cars+on+Route+66",
phaseId:"phase2"},

{day: 5,
date: "Lunedì 10/08/2026",
title: "Grand Canyon South Rim ➔ Monument Valley",
route: "Grand Canyon South Rim ➔ Forest Gump Point ➔ Monument Valley",
km: 344,
time: "4h",
sunrise: "05:43", // ok
sunset: "20:17", // ok
fuso: "Navajo Nation (+1h)",
hotel: "Goulding's Lodge",
desc: "Sveglia presto e alba al <strong>Grand Canyon</strong> (<strong>Mather Point</strong> più comodo perché vicino al Visitor Center) - <strong>Yaki Point</strong> (tranquillo, non affollato) <br>Giro del Grand Canyon (South Rim) in auto sulla <strong>Desert View Drive</strong> con stop ai punti panoramici: <ul style='padding-left: 20px; color: #555; font-size: 11px; margin: 8px 0;'><li>Pipe Creek Vista</li><li>Duck on a Rock Viewpoint</li><li>Grandview Point</li><li>Moran Point</li><li>Lipan Point</li><li>Navajo Point</li><li>Desert View Watchtower</li></ul> Direzione Monument Valley con tappa al <strong>Forrest Gump Point</strong> (orologio +1) e tramonto dal Visitor Center su <strong>The Mittens and Merrick’s Butte</strong><br>Rientro in hotel e cena",
//logistics: "Parcheggio hotel e lotti pubblici vicino al London Bridge / English Village.",
food: ["Goulding’s Stagecoach Dining Room", "Champs Chicken", "Hangar 54 Pizza (ultimi due fast food)"],
pranzo: ["Pranzo on the road: Grand Canyon Village Market & Deli"],
region: "Arizona",
gmaps: "https://maps.google.com/?q=Grand+Canyon+South+Rim",
phaseId: "phase3"
},

{day:6,
date:"Martedì 11/08/2026",
title:"Monument Valley ➔ Horseshoe Bend & Page",
route:"Monument Valley ➔ Horseshoe Bend ➔ Page",
km:249,
time:"4h",
sunrise:"06:34", // ok
sunset:"19:21", // ok
fuso:"Rientro fuso Arizona (-1h)",
hotel:"Knight Inn Page",
desc:"Sveglia presto e alba alla <strong>Monument Valley</strong> dal Visitor Center o dall'alloggio. Giro della Monument Valley in auto sulla <strong>Monument Valley Scenic Drive</strong> con stop ai punti panoramici: <ul style='padding-left: 20px; color: #555; font-size: 11px; margin: 8px 0;'><li>The Mittens and Merrick’s Butte</li><li>Elephant Butte</li><li>Three sisters</li><li>John Ford’s Point</li><li>Camel Butte</li><li>Rain God Mesa</li><li>Totem Pole</li><li>Artist’s Point</li><li>North Window</li><li>The Thumb</li></ul> Direzione <strong>Page</strong> e tramonto a <strong>Horseshoe Bend</strong> (orologio -1)<br>Arrivo in hotel e cena",
//logistics:"Parcheggi lungo strada nelle cittadine Route 66; Hackberry e visitor stop: parcheggi dedicati.",
food:["Big John’s Texas BBQ (live music)","Dam Bar & Grille","El Tapatio","Fiesta Mexicana Restaurant"],
pranzo:["Per pranzo chiosco sulla Scenic Drive: Linda’s Fry Bread stand (vicino John Ford’s Point)"],
region:"Arizona",
gmaps:"https://maps.google.com/?q=Oljato-Monument+Valley,+Arizona+84536,+Stati+Uniti",
phaseId:"phase3"},

{day:7,
date:"Mercoledì 12/08/2026",
title:"Page ➔ Bryce Canyon",
route:"Page ➔ Bryce Canyon",
km:275,
time:"3h28",
sunrise:"06:41", // ok
sunset:"20:24", // ok
fuso:"Mountain Time (Utah) (+1h)",
hotel:"Bryce View Lodge",
desc:"Tour <strong>Lower Antelope Canyon</strong> alle 09:45 (presentarsi 45 min prima)<br> Tappa a <strong>Big Lake Trading Post</strong> per visita a <strong>Biidi The Arch</strong> (Secret Sand Cave) e poi direzione Bryce Canyon con tappe ai punti panoramici <strong>Glen Canyon Dam Overlook</strong> e <strong>Wahweap Overlook</strong> con vista su <strong>Lake Powell</strong> <br> Tramonto da <strong>Ispiration</strong> o <strong>Sunset Point</strong> a Bryce Canyon (10’ in auto da hotel) (orologio +1)<br>Rientro in hotel e cena",
//logistics:"Grand Canyon: Village Lots + navette gratuite. Desert View: parcheggio proprio. Monument Valley: parcheggio The View Hotel. Valley Drive sterrato.",
food:["The Lodge at Bryce Canyon Restaurant", "Cowboy’s Buﬀet and Steak Room","Ebenezer's Barn & Grill"],
pranzo:["Per pranzo valutare se prendere qualcosa a Page dopo il tour oppure fare tappa lungo la strada in direzione Bryce Canyon"],
region:"Arizona & Utah",
gmaps:"https://maps.google.com/?q=Horseshoe+Bend",
phaseId:"phase3"},

{day:8,
date:"Giovedì 13/08/2026",
title:"Bryce Canyon ➔ Zion National Park",
route:"Bryce Canyon ➔ Zion National Park",
km:165,
time:"2h30",
sunrise:"06:43", // ok
sunset:"20:18", // ok
fuso:"Mountain Time (Utah)",
hotel:"Best Western East Zion Thunderbird Lodge",
desc:"Sveglia presto e alba a Bryce Canyon a <strong>Sunrise Point</strong>. Giro di Bryce Canyon in auto con stop ai punti panoramici, consigliato scendere fino a sud e poi fermarsi ai punti panoramici al ritorno (strada chiusa): <ul style='padding-left: 20px; color: #555; font-size: 11px; margin: 8px 0;'><li>Sunset Point</li><li>Inspiration point (vista su Bryce Amphitheatre)</li><li>Bryce point</li><li>Natural Bridge</li><li>Agua Canyon Overlook</li><li>Rainbow Point e Yovimpa Point</li></ul> Dal Sunset Point parte il <strong>Navajo Loop Trail</strong> (a/r 1/1,5 h - consigliato, scendere dal tratto di Wall Street) <br>Direzione <strong>Mount Carmel Junction</strong> con possibili tappe (oltre) da valutare in base al tempo a disposizione e alla stanchezza: <ul style='padding-left: 20px; color: #555; font-size: 11px; margin: 8px 0;'><li>Belly of the Dragon (2’ da hotel)</li><li>Sand Caves (12’ da hotel)</li><li>Coral Pink Sand Dunes State Park (20’ da hotel)</li><li>Kanab (20’ da hotel)</li></ul>Rientro in hotel e cena",
//logistics:"Sunrise Tour: ritrovo 5:15 fuori lobby The View Hotel. Portare Navajo Tribal Park pass ($10/persona). Horseshoe Bend: parcheggio a pagamento, 15-20 min a piedi. Attenzione fuso: lasciando Navajo Nation si guadagna 1h.",
food:["Thunderbird Restaurant"],
pranzo:["Ruby's Inn General Store"],
region:"Utah",
gmaps:"https://maps.google.com/?q=Parco+nazionale+del+Bryce+Canyon",
phaseId:"phase3"},

{day:9,
date:"Venerdì 14/08/2026",
title:"Zion National Park ➔ Las Vegas",
route:"Zion National Park ➔ Las Vegas",
km:318,
time:"3h45",
sunrise:"06:43", // ok
sunset:"19:31", // ok
fuso:"Pacific Time (GMT-7)",
hotel:"Horseshoe Las Vegas",
desc:"Partenza in auto in direzione <strong>Canyon Overlook Trail</strong> per raggiungere il punto panoramico (a/r a piedi 1h circa). Percorrere la <strong>Zion Mount Carmel Highway</strong> e: <ul style='padding-left: 20px; color: #555; font-size: 11px; margin: 8px 0;'><li>Opzione 1: fare la <strong>Zion Canyon Scenic Drive</strong> con navetta (partenza da Visitor Center South Entrance - 9 fermate - a/r tempo di percorrenza 90’) e poi direzione Las Vegas (2 h 38’)</li><li>Opzione 2: tappa a <strong>Kolob Canyon Viewpoint</strong> (distanza in auto da Canyon Overlook Trail 1 h 10’ circa, 80 km) per vista dal punto panoramico e poi direzione Las Vegas (2 h 28’)</li><li>Opzione 3: direzione <strong>Las Vegas</strong> (2 h 40’) (orologio -1)</li></ul> Benvenuti a Las Vegas!<br>Arrivo in hotel, a spasso per la strip e cena",
//logistics:"Parcheggio meeting point tour Canyon X. Kanab: parcheggio hotel gratuito.",
food:["Virgil's Real BBQ","Fogo de Chão Brazilian Steakhouse","Gilley's Saloon","Dance Hall & Bar-B-Que","Hash House A Go Go (anche colazione)","Hot N Juicy Crawfish","Nacho Daddy","Outback Steakhouse","In-N-Out Burger"],
pranzo:["White Mountain Trading Post (di fianco all’hotel)","Sol Foods Supermarket (a Springdale)"],
region:"Utah & Nevada",
gmaps:"https://maps.google.com/?q=Parco+nazionale+di+Zion",
phaseId:"phase3"},

{day:10,
date:"Sabato 15/08/2026",
title:"Las Vegas & Valley of Fire",
route:"Esplorazione Strip & Resort",
km:280,
time:"4h15",
sunrise:"05:59", // ok
sunset:"19:30", // ok
fuso:"Pacific Time (GMT-7)",
hotel:"Horseshoe Las Vegas",
desc:"Raggiungere la <strong>Valley of Fire</strong> tramite <strong>Lake Mead National Recreation Area</strong>. Tappa a <strong>Elephant Rock</strong> con trail di 200 metri, proseguire per la <strong>White Domes Road/ Mouse’s Tank Road</strong> e <strong>Fire Canyon Road</strong> con punti panoramici e tappa ad <strong>Arch Rock</strong> in uscita di ritorno a Las Vegas. (Consigliato partire presto, tempo richiesto mezza giornata)<br>Pomeriggio relax in piscina, a seguire cena e serata sulla Strip",
//logistics:"Bryce Canyon: parcheggi viewpoint congestionati in estate; usare shuttle gratuito del parco.",
food:["Virgil's Real BBQ","Fogo de Chão Brazilian Steakhouse","Gilley's Saloon","Dance Hall & Bar-B-Que","Hash House A Go Go (anche colazione)","Hot N Juicy Crawfish","Nacho Daddy","Outback Steakhouse","In-N-Out Burger"],
pranzo:["In base al programma della giornata"],
bonus: [
  "Gold & Silver Pawn Shop: <a href='https://maps.google.com/?q=713+S+Las+Vegas+Blvd,+Las+Vegas,+NV+89101' target='_blank' rel='noopener' style='color:#e07a5f;font-weight:700'>🗺️ Mappa</a> — 713 S Las Vegas Blvd",
  "Welcome to Las Vegas: <a href='https://maps.google.com/?q=Welcome+to+Fabulous+Las+Vegas+Sign' target='_blank' rel='noopener' style='color:#e07a5f;font-weight:700'>🗺️ Mappa</a> — 5100 Las Vegas Blvd S",
  "Meow Wolf - Omega Mart (Supermercato surreale): <a href='https://maps.google.com/?q=Meow+Wolf+Las+Vegas+Omega+Mart' target='_blank' rel='noopener' style='color:#e07a5f;font-weight:700'>🗺️ Mappa</a> — AREA15, 3215 S Rancho Dr"
],
region:"Nevada",
gmaps:"https://maps.google.com/?q=Elephant+Rock+Valley+of+Fire",
phaseId:"phase4"},

{day:11,
date:"Domenica 16/08/2026",
title:"Las Vegas ➔ Death Valley",
route:"Las Vegas ➔ Red Rock Canyon ➔ Death Valley",
km:286,
time:"3h50",
sunrise:"06:00", // ok
sunset:"19:37", // ok
fuso:"Pacific Time (GMT-7)",
hotel:"The Ranch at Death Valley",
desc:"Direzione <strong>Death Valley</strong> con tappa al <strong>Red Rock Canyon</strong> (mezz’ora da Las Vegas). Giro sulla Scenic Drive a senso unico (durata con soste ai viewpoint 1h circa) <br>Proseguire in direzione <strong>Dantes View</strong> (circa 2h da Las Vegas) e arrivare ad <strong>Artist Palette</strong> per il tramonto (distanza 55’ da Dantes View e 15’ da alloggio)<br>Rientro in hotel e cena",
//logistics:"Zion: parcheggi Springdale/Zion Visitor Center molto richiesti, arrivare presto. Vegas: parcheggio Sahara da verificare (spesso a pagamento).",
food:["The Ranch 1849 Restaurant (con buﬀet)","Last Kind Words Saloon","Wild Rose Tavern","Ice Cream Parlor"],
pranzo:["Per pranzo valutare se prendere qualcosa a Las Vegas oppure fare tappa lungo la strada in direzione Dantes View"],
region:"Nevada & California",
gmaps:"https://maps.google.com/?q=Las+Vegas+Strip,+Nevada,+Stati+Uniti",
phaseId:"phase4"},

{day:12,
date:"Lunedì 17/08/2026",
title:"Death Valley ➔ Sequoia National Park",
route:"Death Valley ➔ Sequoia National Park",
km:629,
time:"7h51",
sunrise:"06:08", // ok
sunset:"19:42", // ok
fuso:"Pacific Time (GMT-7)",
hotel:"The Gateway Restaurant & Lodge",
desc:"Sveglia presto e alba a <strong>Zabriskie Point</strong> (10’ in auto da hotel), tour in auto con tappe ai viewpoint a <strong>Badwater Basin, Devils Golf Course</strong> e <strong>Mesquite Flat Sand Dunes</strong> (entro le 10 consigliato per le alte temperature) <br>Partenza in direzione Sequoia, distanza lunga. Valutare possibili tappe lungo la strada:<ul style='padding-left: 20px; color: #555; font-size: 11px; margin: 8px 0;'><li>Trona Pinnacles (torri di tufo bianche) - raggiungibile in auto</li><li>Red Rock Canyon State Park: in prossimità della Red Cliﬀs Natural Area - raggiungibile in auto</li></ul>Arrivo in hotel e cena",
//logistics:"Auto parcheggiata in hotel. Muoversi con Monorail, a piedi o Uber.",
food:["The Gateway Restaurant & Lodge"],
pranzo:["Per pranzo tappa lungo la strada in direzione Three Rivers"],
region:"California",
gmaps:"https://maps.google.com/?q=Valle+della+Morte,+California,+Stati+Uniti",
phaseId:"phase4"},

{day:13,
date:"Martedì 18/08/2026",
title:"Sequoia National Park ➔ Yosemite National Park",
route:"Sequoia National Park ➔ Yosemite National Park",
km:310,
time:"5h",
sunrise:"06:16", // ok
sunset:"19:46", // ok
fuso:"Pacific Time (GMT-7)",
hotel:"Cedar Lodge",
desc:"Partenza in direzione Giant Forest dove c’è il <strong>General Sherman Tree</strong>, da ingresso sud tramite Ash Mountain Entrance dove c’è il Foothills Visitor Center. Lungo la strada valutare se prima fare tappa a <strong>Tunnel Log</strong> e <strong>Moro Rock</strong> (350 gradini per raggiungere punto panoramico) <br>Dalla zona del General Sherman Tree parte il <strong>Congress Trail</strong>, una sorta di museo a cielo aperto dove è possibile aggirarsi tra gli altri maestosi alberi della Giant Forest: è un semplice loop trail della durata di circa 3 miglia, occorre circa 1 h per farlo tutto <br>Proseguire in direzione Yosemite National Park. Arrivo in hotel e cena",
//logistics:"Parcheggio hotel Bakersfield. Non lasciare mai valigie visibili in auto durante le soste.",
food:["Cedar House Restaurant","Canyon Bar and Grill"],
pranzo:["Totem Market & Gifts (Three Rivers 5’ min in auto)","Lodgepole Market (dentro al parco)"],
region:"California",
gmaps:"https://maps.google.com/?q=Parco+nazionale+di+Sequoia+California,+Stati+Uniti",
phaseId:"phase5"},

{day:14,
date:"Mercoledì 19/08/2026",
title:"Yosemite National Park ➔ San Francisco",
route:"Yosemite National Park ➔ San Francisco",
km:429,
time:"6h40",
sunrise:"06:17", // ok
sunset:"19:56", // ok
fuso:"Pacific Time (GMT-7)",
hotel:"San Remo Hotel",
desc:"Partenza in auto verso le 8 in direzione <strong>Glacier Point</strong> (distanza 1h15 da alloggio) con tappa al punto panoramico <strong>Washburn Point</strong>. Di ritorno tappa a <strong>Tunnel View</strong> e: <ul style='padding-left: 20px; color: #555; font-size: 11px; margin: 8px 0;'><li>Opzione 1: fare <strong>Cook's Meadow Loop</strong> (1,6 km a/r - 45 minuti) con partenza fermata n.6 della navetta (circa 15’ in auto da Tunnel View). Vicino è raggiungibile a piedi anche <strong>Sentinel Bridge</strong> (durata 5-10') e poi direzione San Francisco<br>⚠️ Nota bene: Per Cook’s Meadow Loop valutare di parcheggiare a Yosemite Village Parking per gestire l’affollamento del parcheggio nell’orario centrale della giornata. Prendere navetta da fermata n.1 a n.6</li><li>Opzione 2: aggiungere anche tappa a <strong>El Capitan Meadow</strong> in uscita dalla valle in direzione San Francisco</li><li>Opzione 3: proseguire diretti verso San Francisco</li></ul> Tempo di percorrenza da Yosemite National Park a San Francisco: circa 4h<br>Arrivo in hotel e a spasso per San Francisco zona <strong>Fisherman's Wharf</strong> <br> Da non perdere: <strong>Golden Gate Bridge</strong> (da Golden Gate View Point o da Baker Beach o Marshall’s Beach) e <strong>Pier 39</strong>",
//logistics:"Strade di montagna tortuose ma asfaltate. Evitare percorsi sterrati GPS. Parcheggi interni si riempiono in fretta: entrare la mattina presto.",
food:["Scoma’s Restaurant (tipico pesce)","Historic Seafood Stands at Fisherman’s Wharf (lungo Taylor Street)"],
pranzo:["El Portal Market (per strada in direzione parco)"],
region:"California",
gmaps:"https://maps.google.com/?q=Parco+nazionale+di+Yosemite+California,+Stati+Uniti",
phaseId:"phase5"},

{day:15,
date:"Giovedì 20/08/2026",
title:"San Francisco ➔ Redondo Beach",
route:"San Francisco ➔ Highway 1 ➔ Redondo Beach",
km:733,
time:"9h",
sunrise:"06:30", // ok
sunset:"19:33", // ok
fuso:"Pacific Time (GMT-7)",
hotel:"Ramada by Wyndham Redondo Beach",
desc:"Sveglia presto e ultimo giro per San Francisco. Vista Golden Gate Bridge e Pier 39 (se non visti il giorno prima) <br> Direzione Los Angeles/ Redondo Beach tramite Highway 1 con possibili tappe lungo la costa:<ul style='padding-left: 20px; color: #555; font-size: 11px; margin: 8px 0;'><li>Monterey (Lone Cypress)</li><li>Carmel by the Sea</li><li>Bixby Creek Bridge</li><li>Big Sur</li><li>McWay Falls View Point</li><li>Morro Bay (Morro Rock)</li><li>Santa Barbara</li><li>Malibù (Malibu Pier)</li></ul> Arrivo a Redondo Beach in serata, hotel e cena",
//logistics:"Yosemite estremamente affollato in agosto. Parcheggiare nei parcheggi della Valley e usare navette interne gratuite.",
food:["Old Tony’s","Kincaid’s Fish","Chop & Steakhouse"],
pranzo:["Per pranzo tappa lungo la costa in direzione Redondo Beach"],
region:"California",
gmaps:"https://maps.google.com/?q=Golden+Gate+Bridge+Vista+Point+San+Francisco,+California,+Stati+Uniti",
phaseId:"phase5"},

{day:16,
date:"Venerdì 21/08/2026",
title:"Rientro in Italia",
route:"Redondo Beach ➔ LAX Aereoporto ➔ Milano",
km:15,
time:"20min + volo",
sunrise:"06:19", // ok
sunset:"19:32", // ok
fuso:"Pacific Time (GMT-7)",
hotel:"A bordo del volo di rientro",
desc:"A spasso per Redondo Beach Pier (visita al Redondo Coﬀee & Bait Shop). Trasferimento in aeroporto e riconsegna auto. Volo LAX ➔ Londra ore 15:45",
logistics:"CRITICO: a San Francisco non lasciate MAI bagagli in auto nemmeno 5 minuti. Andare direttamente all'Hertz e poi all'hotel a piedi.",
food:["Cena a bordo dell'aereo"],
pranzo:["Redondo Coﬀee & Bait Shop"],
region:"California",
gmaps:"https://maps.google.com/?q=Aeroporto+Internazionale+di+Los+Angeles",
phaseId:"phase5"}
];
