const itineraryData = [
{day:1,
date:"Giovedì 06/08/2026",
title:"Arrivo a Los Angeles",
route:"LAX ➔ West Hollywood",
km:24,
time:"1h",
sunrise:"06:03",
sunset:"19:56",
fuso:"Pacific Time (GMT-7)",
hotel:"Hotel Ziggy on Sunset West Hollywood",
desc:"Atterraggio a LAX alle 14:55 con volo British da Londra. Considerare 60-90 min per controlli, bagagli, ritiro auto e uscita dall'aeroporto. Trasferimento in hotel e tramonto al Griﬃth Observatory. Sera tranquilla in zona West Hollywood.",
logistics:"Auto prenotata con Alamo.",
transferInfo:"<p>Dopo aver superato i controlli doganali e ritirato i bagagli per raggiungere il lotto auto Alamo uscire dal terminal e seguire i cartelli viola o arancioni con la scritta <strong>Rental Car Shuttles</strong>. Attendere il passaggio dell'autobus navetta gratuito. Il tragitto durerà circa 10-15 minuti. Dirigersi direttamente al lotto di veicoli Alamo per scegliere un veicolo. Le chiavi si troveranno in macchina e la prenotazione sarà verificata alla cabina di uscita del lotto. <br> ⚠️ <strong>Importante:</strong> Aver già fatto il check-in online e inserito i dettagli della carta di credito </p>",
food:["Saddle Ranch Chop House","Mels Drive-In","Carney's Restaurant"],
supermarkets:["Trader Joe's Hollywood/Vine","Sprouts Farmers Market La Brea","Target Hollywood"],
region:"Costa & Città",
gmaps:"https://maps.google.com/?q=Osservatorio+Griffith+Los+Angeles",
phaseId:"phase1"},

{day:2,
date:"Venerdì 07/08/2026",
title:"Beverly Hills, Rodeo Drive, Santa Monica & Venice Beach",
route:"West Hollywood ➔ Beverly Hills ➔ Rodeo Drive ➔ Santa Monica ➔ Venice Beach ➔ West Hollywood",
km:90,
time:"1h",
sunrise:"06:04",
sunset:"19:55",
fuso:"Pacific Time (GMT-7)",
hotel:"Hotel Ziggy on Sunset West Hollywood",
desc:"Partenza dall’hotel in direzione Beverly Hills e Rodeo Drive poi verso Santa Monica per pranzo e passeggiata fino a Venice Beach. Tramonto a Santa Monica. (Distanza hotel - Santa Monica circa 25’). Rientro in hotel, cena e a spasso per la città",
logistics:"Venice Beach Parking Lot o lotti su Pacific Ave; a Santa Monica usare Santa Monica Place Parking o Structure 8; a Malibu usare parcheggi ufficiali spiaggia.",
food:["Pranzo a Pier Burger","Pranzo a The Albright","Saddle Ranch Chop House","Mels Drive-In","Carney's Restaurant"],
supermarkets:["Whole Foods Market Santa Monica","Erewhon Venice"],
region:"Costa & Città",
gmaps:"https://maps.google.com/?q=Santa+Monica+California+Stati+Uniti",
phaseId:"phase1"},

{day:3,
date:"Sabato 08/08/2026",
title:"Route 66 - Kingman",
route:"Los Angeles ➔ Barstow ➔ Amboy ➔ Oatman ➔ Kingman",
km:535,
time:"5h45 + soste",
sunrise:"06:04",
sunset:"19:54",
fuso:"Pacific Time (GMT-7)",
hotel:"Motel 6-Kingman",
desc:"A spasso per la Walk of Fame (Dolby Theatre, TCL Chinese Theatre) prima della partenza in mattinata in direzione Kingman con tappe sulla Route 66 (Barstow città fantasma, Amboy, Oatman). Percorrere la National Trails Hwy (passando per Amboy Roy's Motel & Cafe) e la Oatman Highway con tappa a Oatman Hotel Restaurant & Bar",
logistics:"Osservatorio Griffith: lasciare auto vicino al Teatro Greco. Hollywood: Hollywood & Highland Parking (6801 Hollywood Blvd). Beverly Hills: Parking 461 N Bedford Dr (prime 2h gratis). Bus Sightseeing: fermata Paramount Studios o Dolby Theatre.",
food:["Mr D'z Route 66 Diner (anche colazione)","Black Bear Diner Kingman"],
supermarkets:["Trader Joe's","Sprouts","Target Hollywood"],
region:"Costa & Città",
gmaps:"https://maps.google.com/?q=Roy's+Motel+%26+Cafe",
phaseId:"phase1"},

{day:4,
date:"Domenica 09/08/2026",
title:"Kingman - Grand Canyon",
route:"Kingman ➔ Selingman ➔ Williams ➔ Grand Canyon (Tramonto)",
km:305,
time:"3h15 + soste",
sunrise:"05:59",
sunset:"19:43",
fuso:"Pacific Time (GMT-7)",
hotel:"Maswik Lodge",
desc:"Partenza in mattinata in direzione Grand Canyon con tappe sulla Route 66 (Selingman, Williams). Impostare sul navigatore Peach Spring per arrivare a Selingman passando per la Route 66 storica. Arrivo al Grand Canyon per orario tramonto dal Rim (Hopi Point (più popolare - navetta) - Pima Point (meno aﬀollato - navetta) - Yavapai Point (più comodo perché vicino Visitor Center)). In base all’orario di arrivo valutare la possibilità di fare il giro della Hermit Road con navetta (punto di partenza Village Route Transfer (6’ a piedi da alloggio) - 9 fermate all’andata, 3 al ritorno).",
logistics:"Palm Springs: Downtown Palm Springs Parking. Hotel-parco per tramonto: ~1h senza soste. Evitare lunghe camminate nelle ore centrali per caldo intenso.",
food:["Pranzo in locale tipico lungo la Route 66","Maswik Food Court","Arizona Steakhouse","El Tovar Dining Room"],
supermarkets:["Walmart Supercenter Yucca Valley","Stater Bros. Markets Yucca Valley"],
region:"Deserti & Route 66",
gmaps:"https://maps.google.com/?q=Classic+Cars+on+Route+66",
phaseId:"phase2"},

{day: 5,
date: "Lunedì 10/08/2026",
title: "Grand Canyon South Rim ➔ Monument Valley",
route: "Grand Canyon South Rim ➔ Forest Gump Point ➔ Monument Valley",
km: 281,
time: "3h di viaggio",
sunrise: "05:51",
sunset: "19:34",
fuso: "Pacific Time (Arizona no ora legale)",
hotel: "Goulding's Lodge",
desc: "Sveglia presto e alba dal Grand Canyon (Mather Point più comodo perché vicino Visitor Center) - Yaki Point (tranquillo, non affollato). Giro del Grand Canyon (South Rim) in auto sulla Desert View Drive con stop ai punti panoramici: <ul style='padding-left: 20px; color: #555; font-size: 11px; margin: 8px 0;'><li>Pipe Creek Vista</li><li>Duck on a Rock Viewpoint</li><li>Grandview Point</li><li>Moran Point</li><li>Lipan Point</li><li>Navajo Point</li><li>Desert View Watchtower</li></ul> Direzione Monument Valley con tappa al Forrest Gump Point (orologio +1) e tramonto dal Visitor Center su The Mittens and Merrick’s Butte",
logistics: "Parcheggio hotel e lotti pubblici vicino al London Bridge / English Village.",
food: ["Pranzo on the road: Grand Canyon Village Market & Deli", "Goulding’s Stagecoach Dining Room", "Champs Chicken", "Hangar 54 Pizza (ultimi due fast food)"],
supermarkets: ["Walmart Supercenter Lake Havasu City", "Smith's Food and Drug Lake Havasu City"],
region: "Deserti & Route 66",
gmaps: "https://maps.google.com/?q=Grand+Canyon+South+Rim",
phaseId: "phase2"
},

{day:6,
date:"Martedì 11/08/2026",
title:"Monument Valley ➔ Page & Horseshoe Bend",
route:"Monument Valley ➔ Horseshoe Bend ➔ Page",
km:195,
time:"2h",
sunrise:"05:41",
sunset:"19:21",
fuso:"Mountain Standard Time (No DST)",
hotel:"Knight Inn Page",
desc:"Sveglia presto e alba alla Monument Valley. Giro della Monument Valley in auto sulla Monument Valley Scenic Drive con stop ai punti panoramici: <ul style='padding-left: 20px; color: #555; font-size: 11px; margin: 8px 0;'><li>The Mittens and Merrick’s Butte</li><li>Elephant Butte</li><li>Three sisters</li><li>John Ford’s Point</li><li>Camel Butte</li><li>Rain God Mesa</li><li>Totem Pole</li><li>Artist’s Point</li><li>North Window</li><li>The Thumb</li></ul> Direzione Page e tramonto a Horseshoe Bend (orologio -1)",
logistics:"Parcheggi lungo strada nelle cittadine Route 66; Hackberry e visitor stop: parcheggi dedicati.",
food:["Per pranzo chiosco sulla Scenic Drive: Linda’s Fry Bread stand (vicino John Ford’s Point)","Big John’s Texas BBQ","Dam Bar & Grille","El Tapatio","Fiesta Mexicana Restaurant"],
supermarkets:["Safeway Williams AZ","Dollar General Williams AZ"],
region:"Deserti & Route 66",
gmaps:"https://maps.google.com/?q=Oljato-Monument+Valley,+Arizona+84536,+Stati+Uniti",
phaseId:"phase2"},

{day:7,
date:"Mercoledì 12/08/2026",
title:"Page ➔ Bryce Canyon",
route:"Page ➔ Bryce Canyon",
km:243,
time:"2h35 + soste",
sunrise:"05:37 / 06:26 (MV)",
sunset:"19:21 / 20:13 (MV)",
fuso:"Navajo Nation (+1h vs Arizona)",
hotel:"Bryce View Lodge",
desc:"Tour Lower Antelope Canyon alle 09:45 (presentarsi 45 min prima). Tappa a Big Lake Trading Post per visita a Biidi The Arch (Secret Sand Cave) e poi direzione Bryce Canyon con tappa al punto panoramico Glen Canyon Dam Overlook e Wahweap Overlook con vista su Lake Powell. Tramonto da Ispiration o Sunset Point a Bryce Canyon (10’ in auto da hotel) (orologio +1)",
logistics:"Grand Canyon: Village Lots + navette gratuite. Desert View: parcheggio proprio. Monument Valley: parcheggio The View Hotel. Valley Drive sterrato.",
food:["Per pranzo valutare se prendere qualcosa a Page dopo il tour oppure fare tappa lungo la strada in direzione Bryce Canyon","The Lodge at Bryce Canyon Restaurant", "Cowboy’s Buﬀet and Steak Room","Ebenezer's Barn & Grill"],
supermarkets:["Safeway Williams","Goulding's Grocery (Monument Valley)"],
region:"I Canyon del Sud-Ovest",
gmaps:"https://maps.google.com/?q=Horseshoe+Bend",
phaseId:"phase3"},

{day:8,
date:"Giovedì 13/08/2026",
title:"Bryce Canyon ➔ Zion National Park",
route:"Bryce Canyon ➔ Zion National Park",
km:92,
time:"1h",
sunrise:"06:27 / 05:39",
sunset:"20:12 / 19:16",
fuso:"Rientro fuso Arizona (-1h)",
hotel:"Best Western East Zion Thunderbird Lodge",
desc:"Sveglia presto e alba al Bryce Canyon a Sunrise Point. Giro di Bryce Canyon in auto con stop ai punti panoramici, consigliato scendere fino a sud e poi fermarsi ai punti panoramici al ritorno (strada chiusa): <ul style='padding-left: 20px; color: #555; font-size: 11px; margin: 8px 0;'><li>Sunset Point</li><li>Inspiration point (vista su Bryce Amphitheatre)</li><li>Bryce point</li><li>Natural Bridge</li><li>Agua Canyon Overlook</li><li>Rainbow Point e Yovimpa Point</li></ul> Dal Sunset Point parte Navajo Loop Trail (a/r 1/1,5 h - consigliato, scendere dal tratto di Wall Street). Direzione Mount Carmel Junction con possibili tappe (oltre) da valutare in base al tempo a disposizione e alla stanchezza: <ul style='padding-left: 20px; color: #555; font-size: 11px; margin: 8px 0;'><li>Belly of the Dragon (2’ da hotel)</li><li>Sand Caves (12’ da hotel)</li><li>Coral Pink Sand Dunes State Park (20’ da hotel)</li><li>Kanab (20’ da hotel)</li></ul>",
logistics:"Sunrise Tour: ritrovo 5:15 fuori lobby The View Hotel. Portare Navajo Tribal Park pass ($10/persona). Horseshoe Bend: parcheggio a pagamento, 15-20 min a piedi. Attenzione fuso: lasciando Navajo Nation si guadagna 1h.",
food:["Pranzo on the road","Thunderbird Restaurant"],
supermarkets:["Ruby's Inn General Store"],
region:"I Canyon del Sud-Ovest",
gmaps:"https://maps.google.com/?q=Parco+nazionale+del+Bryce+Canyon",
phaseId:"phase3"},

{day:9,date:"Venerdì 14/08/2026",title:"Page ➔ Antelope Canyon X ➔ Kanab",route:"Page ➔ Antelope Canyon X ➔ Kanab",km:130,time:"1h45-2h15 + tour",sunrise:"05:40 / 06:44",sunset:"19:15 / 20:20",fuso:"Mountain Time / Utah (+1h)",hotel:"La Quinta Inn & Suites Kanab",desc:"Tour Antelope Canyon X alle 11:40 (già prenotato, presentarsi 30 min prima). Dopo il tour, pranzo e trasferimento a Kanab. Benvenuti in Utah!",logistics:"Parcheggio meeting point tour Canyon X. Kanab: parcheggio hotel gratuito.",food:["Pranzo rapido a Page","Peekaboo Canyon Wood Fired Kitchen Kanab (ottimo veg e pizza)","Rocking V Cafe Kanab (veg-friendly)"],supermarkets:["Honey's Marketplace Kanab","Glazier's Market Kanab"],region:"I Canyon del Sud-Ovest",gmaps:"https://maps.google.com/?q=Antelope+Canyon+X+Page",phaseId:"phase3"},
{day:10,date:"Sabato 15/08/2026",title:"Kanab ➔ Bryce Canyon A/R",route:"Kanab ➔ Bryce Canyon ➔ Kanab",km:315,time:"3h30-4h totali di guida",sunrise:"06:37",sunset:"20:16",fuso:"Mountain Time (Utah)",hotel:"La Quinta Inn & Suites Kanab",desc:"Partenza ore 08:00, arrivo Bryce Canyon ~09:30. Viewpoint principali: Sunset Point, Navajo Loop/Queen's Garden trail, Bryce Point. Rientro a Kanab tardo pomeriggio.",logistics:"Bryce Canyon: parcheggi viewpoint congestionati in estate; usare shuttle gratuito del parco.",food:["Pranzo al sacco (comprare snack a Kanab) o Bryce Canyon Lodge","Rientro a Kanab: locali provati il giorno prima"],supermarkets:["Honey's Marketplace Kanab"],region:"I Canyon del Sud-Ovest",gmaps:"https://maps.google.com/?q=Bryce+Canyon+National+Park",phaseId:"phase3"},
{day:11,date:"Domenica 16/08/2026",title:"Kanab ➔ Zion ➔ Las Vegas",route:"Kanab ➔ Zion National Park ➔ Las Vegas",km:355,time:"4h30-5h30 + visita Zion",sunrise:"06:40 / 05:52",sunset:"20:16 / 19:35",fuso:"Pacific Time / Nevada (-1h)",hotel:"Sahara Las Vegas",desc:"Partenza presto per Zion. Da Springdale/Zion Canyon usare navette obbligatorie. Visita leggera: Riverside Walk o viewpoint accessibili. Dopo pranzo partenza per Las Vegas, arrivo tardo pomeriggio.",logistics:"Zion: parcheggi Springdale/Zion Visitor Center molto richiesti, arrivare presto. Vegas: parcheggio Sahara da verificare (spesso a pagamento).",food:["Springdale: cafés vegetariani","Crossroads Kitchen Las Vegas (vegano favoloso in Resorts World)","Truth & Tonic Wellness Cafe","Chef Kenny's Vegan Asian"],supermarkets:["Target Pharmacy vicino Strip","Smith's Food and Drug Las Vegas","Whole Foods Market Las Vegas"],region:"I Canyon del Sud-Ovest",gmaps:"https://maps.google.com/?q=Sahara+Las+Vegas+Hotel",phaseId:"phase3"},
{day:12,date:"Lunedì 17/08/2026",title:"Las Vegas",route:"Esplorazione Strip & Resort",km:10,time:"Nessun trasferimento impegnativo",sunrise:"05:53",sunset:"19:34",fuso:"Pacific Time (GMT-7)",hotel:"Sahara Las Vegas",desc:"Giornata Strip, hotel tematici, Bellagio Fountains, Venetian, Wynn/Encore. Visita il famoso Gold & Silver Pawn Shop (Pawn Stars). Alternare interni climatizzati ed esterni per il caldo. Serata sulla Strip.",logistics:"Auto parcheggiata in hotel. Muoversi con Monorail, a piedi o Uber.",food:["Tacotarian Las Vegas (Tacos vegan incredibili)","Chef Kenny's Vegan Asian","Graze Kitchen (Piatti plant-based)"],supermarkets:["Target / Walgreens / CVS sulla Strip"],bonus:["Gold & Silver Pawn Shop (Pawn Stars): <a href='https://maps.google.com/?q=713+S+Las+Vegas+Blvd,+Las+Vegas,+NV+89101' target='_blank' rel='noopener' style='color:#e07a5f;font-weight:700'>🗺️ Mappa</a> — 713 S Las Vegas Blvd"],region:"Las Vegas & Trasferimento",gmaps:"https://maps.google.com/?q=Las+Vegas+Strip",phaseId:"phase4"},
{day:13,date:"Martedì 18/08/2026",title:"Las Vegas ➔ Bakersfield",route:"Las Vegas ➔ Barstow ➔ Mojave ➔ Tehachapi ➔ Bakersfield",km:460,time:"4h30-5h di guida pura",sunrise:"05:54 / 06:12",sunset:"19:32 / 19:54",fuso:"Pacific Time (GMT-7)",hotel:"La Quinta Inn & Suites Bakersfield North",desc:"Trasferimento diretto via I-15 S e CA-58 W. Niente Death Valley. Partenza 08:30-09:00. Fare pieno prima di uscire da Vegas o a Barstow. Sosta a Peggy Sue's 50's Diner.",logistics:"Parcheggio hotel Bakersfield. Non lasciare mai valigie visibili in auto durante le soste.",food:["Pranzo al sacco da Las Vegas","Tehachapi: sosta caffè e opzioni veg","Vida Vegan Co. Bakersfield"],supermarkets:["Trader Joe's Bakersfield","Sprouts Farmers Market Bakersfield","Walmart / Target Bakersfield"],region:"Las Vegas & Trasferimento",gmaps:"https://maps.google.com/?q=La+Quinta+Bakersfield+North",phaseId:"phase4"},
{day:14,date:"Mercoledì 19/08/2026",title:"Bakersfield ➔ Sequoia ➔ Visalia",route:"Bakersfield ➔ Sequoia National Park ➔ Visalia",km:260,time:"4h-5h + visita parco",sunrise:"06:13",sunset:"19:52",fuso:"Pacific Time (GMT-7)",hotel:"La Quinta Inn & Suites Visalia/Sequoia Gateway",desc:"Partenza presto da Bakersfield. Entrare al Sequoia NP da Ash Mountain (Highway 198). Giant Forest, General Sherman Tree, passeggiate facili. Uscire verso Visalia tardo pomeriggio.",logistics:"Strade di montagna tortuose ma asfaltate. Evitare percorsi sterrati GPS. Parcheggi interni si riempiono in fretta: entrare la mattina presto.",food:["Pranzo al sacco nel parco (Lodgepole Market)","Pita Kabob Visalia","The Planing Mill Visalia (pizze e insalate)"],supermarkets:["Sprouts Farmers Market Visalia","Save Mart / Target Visalia"],region:"Foreste & San Francisco",gmaps:"https://maps.google.com/?q=General+Sherman+Tree+Sequoia",phaseId:"phase5"},
{day:15,date:"Giovedì 20/08/2026",title:"Visalia ➔ Yosemite ➔ Oakhurst",route:"Visalia ➔ Yosemite Valley ➔ Oakhurst",km:305,time:"5h-6h + parco",sunrise:"06:11",sunset:"19:51",fuso:"Pacific Time (GMT-7)",hotel:"Yosemite Southgate Hotel & Suites",desc:"Partenza all'alba verso South Entrance di Yosemite. Scegliere tra Yosemite Valley (El Capitan, Yosemite Falls) o Glacier Point/Mariposa Grove. Tardo pomeriggio trasferimento a Oakhurst.",logistics:"Yosemite estremamente affollato in agosto. Parcheggiare nei parcheggi della Valley e usare navette interne gratuite.",food:["Pranzo al sacco (code ai bar del parco >1h!)","South Gate Brewing Company Oakhurst","Glow Café Oakhurst"],supermarkets:["Vons Oakhurst","Raley's Oakhurst"],region:"Foreste & San Francisco",gmaps:"https://maps.google.com/?q=Yosemite+Valley",phaseId:"phase5"},
{day:16,date:"Venerdì 21/08/2026",title:"Oakhurst ➔ SF & Riconsegna Auto",route:"Oakhurst ➔ San Francisco (Mason St Hertz)",km:325,time:"4h-5h di viaggio",sunrise:"06:23",sunset:"20:01",fuso:"Pacific Time (GMT-7)",hotel:"Hotel Spero (poi Timbri Hotel)",desc:"Partenza mattina presto da Oakhurst. Obiettivo tassativo: riconsegnare auto Hertz Mason Street entro le 14:00 (ufficio chiude alle 15:00). Hotel Spero a pochi minuti a piedi. Check-in e relax.",logistics:"CRITICO: a San Francisco non lasciate MAI bagagli in auto nemmeno 5 minuti. Andare direttamente all'Hertz e poi all'hotel a piedi.",food:["Pranzo veloce on the road","Golden Era Vegan SF (asiatica vegana vicino Union Square)","Shizen Vegan Sushi Bar (sushi vegano straordinario, prenotare!)"],supermarkets:["Trader Joe's Union Square","Target / CVS Union Square"],region:"Foreste & San Francisco",gmaps:"https://maps.google.com/?q=Hotel+Spero+San+Francisco",phaseId:"phase5"},
{day:17,date:"Sabato 22/08/2026",title:"San Francisco (Sausalito)",route:"Ferry/Traghetto/Piedi",km:15,time:"Tempi variabili",sunrise:"06:24",sunset:"20:00",fuso:"Pacific Time (GMT-7)",hotel:"Timbri Hotel San Francisco - 33 Turk St",desc:"Opzione panoramica traghetto: Ferry Building, Embarcadero, Fisherman's Wharf, traghetto per Sausalito con vista Golden Gate dal mare.",logistics:"Muoversi a piedi e mezzi pubblici. Ferry Terminal: arrivare con anticipo.",food:["Greens Restaurant (Storico vegetariano a Fort Mason, vista golfo)","Ferry Building: cibo veg d'asporto","Wildseed SF (Cucina vegetale alto livello)"],supermarkets:["Rainbow Grocery SF (Paradiso bio, naturale e vegano)"],region:"Foreste & San Francisco",gmaps:"https://maps.google.com/?q=Timbri+Hotel+San+Francisco",phaseId:"phase5"},
{day:18,date:"Martedì 18/08/2026",title:"San Francisco Città",route:"Esplorazione Quartieri (No Auto)",km:10,time:"Piedi, Cable Car e bus",sunrise:"06:25",sunset:"19:58",fuso:"Pacific Time (GMT-7)",hotel:"Timbri Hotel San Francisco",desc:"Quartieri celebri: Union Square, Chinatown, North Beach, Coit Tower, Lombard Street, Fisherman's Wharf. Cable Car la mattina presto per evitare code. Pomeriggio: Painted Ladies o Mission District.",logistics:"Attenzione alle pendenze di SF. Alternare camminata con autobus o brevi Uber.",food:["Nourish Cafe (Insalate e bowl biologiche)","Shizen Vegan Sushi (seconda chance!)","Golden Era Vegan"],supermarkets:["Trader Joe's / Target vicino hotel"],region:"Foreste & San Francisco",gmaps:"https://maps.google.com/?q=Lombard+Street+San+Francisco",phaseId:"phase5"},
{day:19,date:"Lunedì 19/08/2026",title:"Alcatraz + San Francisco",route:"Pier 33 ➔ Alcatraz Island ➔ SF",km:10,time:"Ferry per Alcatraz + Piedi",sunrise:"06:26",sunset:"19:57",fuso:"Pacific Time (GMT-7)",hotel:"Timbri Hotel San Francisco",desc:"Tour Alcatraz ore 11:00 (già prenotato). Arrivare a Pier 33 30-45 min prima. Dopo il tour, pranzo all'Embarcadero. Pomeriggio libero per shopping o Exploratorium esterno.",logistics:"Pier 33: a piedi, tram storico linea F o Uber dall'hotel.",food:["Pranzo chioschi biologici Ferry Building","Wildseed SF (Ultima cena americana plant-based)"],supermarkets:["CVS / Walgreens per snack ultimo minuto"],region:"Foreste & San Francisco",gmaps:"https://maps.google.com/?q=Alcatraz+Landing+Pier+33",phaseId:"phase5"},
{day:20,date:"Martedì 20/08/2026",title:"Rientro in Italia",route:"San Francisco Centro ➔ SFO Aeroporto",km:22,time:"30-60 min o BART",sunrise:"06:27",sunset:"19:55",fuso:"Pacific Time (GMT-7)",hotel:"A bordo del volo di rientro",desc:"Ultima mattina a San Francisco. Volo SFO ➔ Lisbona ore 16:30. Presentarsi a SFO entro le 13:30. Lasciare il centro entro le 12:30.",logistics:"Nessun parcheggio. Trasferimento a SFO: taxi, Uber o BART se comoda con valigie.",food:["Pranzo leggero in hotel o in aeroporto","Comprare snack vegani prima dei controlli SFO"],supermarkets:["Target o farmacia per snack da viaggio"],region:"Trasferimento",gmaps:"https://maps.google.com/?q=San+Francisco+International+Airport",phaseId:"phase5"}
];
